import type { PokemonType } from './types'

// One released, non-shadow species in public/data/pokemon-index.json
// (generated by scripts/build-pokemon-index.mjs).
export interface PokemonEntry {
  id: string
  dex: number
  name: string
  nameEn: string
  types: PokemonType[]
  atk: number
  def: number
  hp: number
  fast: string[]
  charged: string[]
  sprite: string | null
}

export interface PokemonIndex {
  list: PokemonEntry[]
  byId: Map<string, PokemonEntry>
  /** reverse index: move id -> species ids that learn it */
  reverse: Record<string, string[]>
}

let cache: Promise<PokemonIndex> | null = null

// Lazy-fetch the generated indexes once (on first use), then memoize. `base` is
// import.meta.env.BASE_URL so the paths respect a deployed base path.
export function loadPokemonIndex(base: string): Promise<PokemonIndex> {
  if (!cache) {
    cache = (async () => {
      const [list, reverse] = await Promise.all([
        fetch(`${base}data/pokemon-index.json`).then((r) => r.json() as Promise<PokemonEntry[]>),
        fetch(`${base}data/move-pokemon.json`).then((r) => r.json() as Promise<Record<string, string[]>>),
      ])
      return { list, byId: new Map(list.map((p) => [p.id, p])), reverse }
    })()
  }
  return cache
}
