import type { PokemonType } from './types'

// One released, non-shadow species in public/data/pokemon-index.json
// (generated by scripts/build-pokemon-index.mjs).
export interface PokemonEntry {
  id: string
  dex: number
  name: string
  nameEn: string
  types: PokemonType[]
  atk: number
  def: number
  hp: number
  fast: string[]
  charged: string[]
  sprite: string | null
  family: string | null
}

export interface PokemonIndex {
  list: PokemonEntry[]
  byId: Map<string, PokemonEntry>
  /** reverse index: move id -> species ids that learn it */
  reverse: Record<string, string[]>
}

let cache: Promise<PokemonIndex> | null = null

// Lazy-fetch the generated indexes once (on first use), then memoize. `base` is
// import.meta.env.BASE_URL so the paths respect a deployed base path.
export function loadPokemonIndex(base: string): Promise<PokemonIndex> {
  if (!cache) {
    cache = (async () => {
      const json = async (p: string) => {
        const r = await fetch(`${base}${p}`)
        if (!r.ok) throw new Error(`fetch ${p}: ${r.status}`)
        return r.json()
      }
      const [list, reverse] = (await Promise.all([
        json('data/pokemon-index.json'),
        json('data/move-pokemon.json'),
      ])) as [PokemonEntry[], Record<string, string[]>]
      return { list, byId: new Map(list.map((p) => [p.id, p])), reverse }
    })().catch((e) => {
      cache = null // let a later call retry after a transient failure
      throw e
    })
  }
  return cache
}
