// Per-league pvpoke ranking lookups (generated by scripts/build-rankings.mjs),
// lazy-fetched on demand and memoized per league.
export type League = 'gl' | 'ul' | 'ml'
export const LEAGUES: League[] = ['gl', 'ul', 'ml']

export interface Ranking {
  score: number
  moveset: string[] // [fast, charged, charged] (lowercased move ids)
  matchups: string[] // species ids it beats
  counters: string[] // species ids that beat it
}
export type Rankings = Record<string, Ranking>

const cache: Partial<Record<League, Promise<Rankings>>> = {}

export function loadRankings(base: string, league: League): Promise<Rankings> {
  if (!cache[league]) {
    cache[league] = fetch(`${base}data/rankings-${league}.json`)
      .then((r) => {
        if (!r.ok) throw new Error(`rankings ${league}: ${r.status}`)
        return r.json() as Promise<Rankings>
      })
      .catch((e) => {
        cache[league] = undefined
        throw e
      })
  }
  return cache[league]!
}
