// Regenerate src/lib/cpm.ts (CP Multiplier per level) from the authoritative
// PokeMiners game master. Whole-level CPMs come straight from the game master;
// half-levels use the in-game interpolation cpm(L+0.5) = sqrt((cpm(L)²+cpm(L+1)²)/2).
//
//   node scripts/build-cpm.mjs
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const URL = 'https://raw.githubusercontent.com/PokeMiners/game_masters/master/latest/latest.json'
const MAX_LEVEL = 51 // 50 max + 1 (best buddy)

const gm = await (await fetch(URL)).json()
const tpl = gm.find((x) => x.templateId === 'PLAYER_LEVEL_SETTINGS')
const whole = tpl?.data?.playerLevel?.cpMultiplier // index 0 = level 1
if (!whole?.length) throw new Error('cpMultiplier not found in game master')
const cpm = (L) => whole[L - 1]

const out = []
for (let L = 1; L <= MAX_LEVEL; L += 0.5) {
  if (Number.isInteger(L)) out.push(cpm(L))
  else {
    const lo = cpm(Math.floor(L))
    const hi = cpm(Math.ceil(L))
    out.push(Math.sqrt((lo * lo + hi * hi) / 2))
  }
}

const body = `// AUTO-GENERATED by scripts/build-cpm.mjs — do not edit by hand.
// CP Multiplier by level, 1.0..${MAX_LEVEL}.0 in 0.5 steps. Index i maps to level 1 + i*0.5.
// Whole levels: PokeMiners game master. Half levels: sqrt((cpm(L)²+cpm(L+1)²)/2).
export const CPM: number[] = [
${out.map((v) => '  ' + v).join(',\n')},
]

export const MAX_LEVEL = ${MAX_LEVEL}
export const levelForIndex = (i: number) => 1 + i * 0.5
export const indexForLevel = (level: number) => Math.round((level - 1) * 2)
`
writeFileSync(resolve(__dirname, '../src/lib/cpm.ts'), body)
console.log(`wrote src/lib/cpm.ts — ${out.length} entries (L1..L${MAX_LEVEL})`)
